import Head from 'next/head';
import Image from 'next/image';
import { PostCard, PostWidget, Categories } from '../components';

const posts = [
	{ title: 'React-Testing', excerpt: 'Learn React Testing' },
	{ title: 'React with Tailwind', excerpt: 'Learn React with Tailwind ' },
];

export default function Home() {
	return (
		<div className="container mx-auto px-10 mb-8 ">
			<Head>
				<title>CMS Blog</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="grid grid-cols-1 lg:grid-cols-12 gap-12 ">
				<div className="col-span-1 lg:col-span-8 ">
					{posts.map((post) => (
						<PostCard post={post} key={post.title} />
					))}
				</div>
				<div className="col-span-1 lg:col-span-4 ">
					<div className="lg:sticky relative top-8 ">
						<PostWidget />
						<Categories />
					</div>
				</div>
			</div>
		</div>
	);
}
